### ISSUE TITLE
Doesn't work for Android Studio 4.2.2

### ISSUE THREAD

**Issue by ultraon** [jvmlet/reveal-dependency-plugin#1]
Hello, I've tried this plugin v.1.3.6 in Android Studio 4.2.2, and there is no menu item over gradle task name.
![Screenshot 2021-07-16 at 23 32 27](https://user-images.githubusercontent.com/6382537/126006181-35713bb9-2d8d-45bc-9aa9-d7cf8c3c5e0d.png)
![Screenshot 2021-07-16 at 23 36 24](https://user-images.githubusercontent.com/6382537/126006189-91888ac8-bedc-4a48-92b4-d8621ae6e9d3.png)

**Comment by jvmlet** [comment]
Gradle dependency tree context item was added in 1.3.9
