### ISSUE TITLE
Right-Clicking Testing Tasks Expands External Libraries

### ISSUE THREAD

**Issue by hotn** [jvmlet/reveal-dependency-plugin#4]
The plugin is causing the external dependencies list to expand when right-clicking on "check" and "test" Gradle tasks, not just right-clicking on Gradle dependencies as described in this plugin's documentation. This behavior only happens on those two tasks, not any of the other verification tasks.

**Comment by jvmlet** [comment]
Closing as fixed, verified with 1.7.0
